# Generated by Django 2.2 on 2021-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLoader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Оригинальное изображение')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Изображеие',
                'verbose_name_plural': 'Изображеия',
                'ordering': ['-published'],
            },
        ),
    ]
